version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    env_file:
      - ./.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env