# Generated by Django 3.1.2 on 2020-10-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0002_project_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(db_index=True, help_text='The gid of this object in Asana.', max_length=31, null=True)),
                ('description', models.TextField(verbose_name='Task description')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='user.user', verbose_name='Assignee')),
                ('projects', models.ManyToManyField(related_name='tasks', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
