# Generated by Django 3.1.2 on 2020-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
